"""
editor/scripting/constants.py — Génère constants.h depuis la liste des
Constant déclarées explicitement dans le projet (project.constants).

Contrairement aux globals (variables modifiables, extern g_<nom> + globals.c),
une constante est figée à la compilation : elle vit entièrement dans le
header sous forme de `static const <type> CONST_<NOM> = <valeur>;`, sans
fichier .c ni symbole externe à définir.
"""

from __future__ import annotations
from pathlib import Path

from .globals import _C_TYPES
from core.app_info import APP_NAME
import codegen.build_output as build_output


def generate_constants_h(constants_) -> str:
    """constants_ : list[Constant] (duck-typed: .name, .type, .value)"""
    lines = [
        "/* constants.h — constants explicitly declared in the project */",
        f"/* Generated by {APP_NAME} — do not edit */",
        "",
        "#ifndef CONSTANTS_H",
        "#define CONSTANTS_H",
        "",
    ]
    if constants_:
        for c in constants_:
            c_type = _C_TYPES.get(c.type, "int")
            lines.append(f"static const {c_type} CONST_{c.name.upper()} = {int(c.value)};")
    else:
        lines.append("/* no constant declared in this project */")
    lines += ["", "#endif /* CONSTANTS_H */", ""]
    return "\n".join(lines)


def write_constants(src_dir: Path, constants_) -> list[str]:
    """
    Écrit constants.h dans src_dir depuis la liste de Constant.
    Retourne la liste des noms (utile pour CodegenContext).
    """
    build_output.write(src_dir / "constants.h", generate_constants_h(constants_))
    return [c.name for c in constants_]
